---
abstract: 'Postcode.nl Webshop API'
author:
  - 'Peter Stuifzand <peter@stuifzand.eu>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-PostcodeNL-WebshopAPI
provides:
  Net::PostcodeNL::WebshopAPI:
    file: lib/Net/PostcodeNL/WebshopAPI.pm
    version: 0.2
  Net::PostcodeNL::WebshopAPI::Response:
    file: lib/Net/PostcodeNL/WebshopAPI/Response.pm
    version: 0
requires:
  JSON::XS: 2.33
  LWP::UserAgent: 6.04
  URI::Template: 0.16
  perl: v5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.2
